/**
 * Event Schema - Detection Event Data Contract
 *
 * SCHEMA ONLY - NO LOGIC ALLOWED
 *
 * This interface defines the structure of detection events sent FROM the client
 * TO the Command Centre for aggregation and analysis.
 *
 * CRITICAL ARCHITECTURE:
 * ----------------------
 * CLIENT ➜ COMMAND CENTRE (ONE-WAY OUTBOUND)
 *
 * - Client sends detection events outward only
 * - Client NEVER receives intelligence, models, or training data back
 * - Client remains inference-only
 * - All learning happens in the Command Centre
 *
 * This is a pure data contract with no validation, logic, or runtime behavior.
 *
 * DO NOT:
 * - Add validation logic
 * - Add runtime behavior
 * - Add model distribution logic
 * - Add bi-directional communication
 * - Implement learning on the client
 */

/**
 * Detection event payload sent from client to Command Centre.
 *
 * Represents a single license plate detection event captured by a client
 * deployment camera.
 */
export interface DetectionEventSchema {
  /**
   * Unique identifier for this detection event.
   * Generated by the client at time of detection.
   */
  event_id: string;

  /**
   * Identifier of the camera that captured this event.
   */
  camera_id: string;

  /**
   * Identifier of the city/deployment sending this event.
   */
  city_id: string;

  /**
   * When the detection occurred (ISO 8601 format).
   * Example: "2024-01-15T14:30:00Z"
   */
  timestamp: string;

  /**
   * Detected license plate text.
   * Null if detection failed or confidence was too low.
   */
  plate_text: string | null;

  /**
   * Model confidence score (0.0 to 1.0).
   * Represents the inference model's confidence in the detection.
   */
  confidence: number;

  /**
   * Optional metadata about the detection.
   */
  metadata?: {
    /**
     * Image dimensions if available.
     */
    image_width?: number;
    image_height?: number;

    /**
     * Bounding box coordinates if available.
     */
    bbox?: {
      x: number;
      y: number;
      width: number;
      height: number;
    };

    /**
     * Model version used for this detection.
     */
    model_version?: string;

    /**
     * Additional context from the detection.
     */
    [key: string]: any;
  };
}

/**
 * REMINDER: This is a schema-only file.
 *
 * - No validation logic
 * - No runtime behavior
 * - No learning or training
 * - Client sends data outward only
 * - Client never receives intelligence back
 */
